#!/usr/bin/env python3
"""
Create a new EVT6 dataset directory (protocol variant) from an existing EVT6 directory.

Why:
- You already have a prepared EVT6 dataset dir (e.g. diting2_evt6_paperalign) with waves_non/*.npy.
- For paper-aligned evaluation, some runs use test_from_val (test==val), which is NOT a held-out test.
- This script creates a new directory with:
  - meta_evt6.csv (copied/symlinked)
  - meta_evt6_{train,val,test}.csv generated by strict per-class split
  - waves_non symlink (so no recompute / no extra disk)
  - selection_record_evt6.json updated for traceability

Typical usage:
python tools/create_evt6_protocol_dir.py \
  --src_dir /path/to/diting2_evt6 \
  --dst_dir /path/to/diting2_evt6_holdout \
  --seed 100 --val_per_class 300 --test_per_class 300
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
from pathlib import Path
from typing import Dict, Any

import numpy as np
import pandas as pd


def _safe_symlink(src: Path, dst: Path) -> None:
    if dst.exists() or dst.is_symlink():
        return
    dst.parent.mkdir(parents=True, exist_ok=True)
    os.symlink(str(src), str(dst))


def _safe_copy(src: Path, dst: Path) -> None:
    if dst.exists():
        return
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(str(src), str(dst))


def _load_record(path: Path) -> Dict[str, Any]:
    if not path.exists():
        return {}
    try:
        return json.load(open(path, "r", encoding="utf-8"))
    except Exception:
        return {}


def _strict_split_evt6(
    df: pd.DataFrame,
    seed: int,
    val_per_class: int,
    test_per_class: int,
    train_per_class: int | None,
) -> Dict[str, pd.DataFrame]:
    """
    Mirrors the strict split logic in tools/prepare_diting2_evt6.py:
    - If class has enough samples: take fixed val/test; train=remaining or capped by train_per_class.
    - Small class: ratio split 0.1/0.1 (use all, keep at least 1 train).
    """
    rng = np.random.default_rng(int(seed))
    parts = {"train": [], "val": [], "test": []}

    for cls in range(6):
        sub = df[df["_evt6"] == cls]
        n = len(sub)
        if n == 0:
            continue

        if n >= (val_per_class + test_per_class + 1):
            v = int(val_per_class)
            t = int(test_per_class)
            remain = n - v - t
            tr = remain if train_per_class is None else min(int(train_per_class), remain)
        else:
            v = int(round(0.1 * n))
            t = int(round(0.1 * n))
            if v + t >= n:
                v = max(0, n - 1)
                t = 0
            tr = n - v - t
            # keep "all-in" for small classes
            if train_per_class is not None:
                tr = n - v - t

        idx = sub.index.to_numpy()
        rng.shuffle(idx)
        val_idx = idx[:v]
        test_idx = idx[v : v + t]
        train_idx = idx[v + t : v + t + tr]

        parts["train"].append(df.loc[train_idx])
        parts["val"].append(df.loc[val_idx])
        parts["test"].append(df.loc[test_idx])

    out: Dict[str, pd.DataFrame] = {}
    for split in ("train", "val", "test"):
        sdf = pd.concat(parts[split], axis=0).reset_index(drop=True)
        sdf = sdf.sample(frac=1.0, random_state=int(seed)).reset_index(drop=True)
        out[split] = sdf
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src_dir", required=True, help="Existing EVT6 dataset dir (has meta_evt6.csv, waves_non/)")
    ap.add_argument("--dst_dir", required=True, help="New EVT6 dataset dir to create")
    ap.add_argument("--seed", type=int, default=100)
    ap.add_argument("--val_per_class", type=int, default=300)
    ap.add_argument("--test_per_class", type=int, default=300)
    ap.add_argument("--train_per_class", type=int, default=0, help="0=use all remaining after val/test")
    ap.add_argument(
        "--test_from_val",
        action="store_true",
        help="Paper-align mode: overwrite meta_evt6_test.csv == meta_evt6_val.csv",
    )
    ap.add_argument(
        "--link_mode",
        default="symlink",
        choices=["symlink", "copy"],
        help="How to bring meta_evt6.csv and waves_non into dst_dir",
    )
    args = ap.parse_args()

    src = Path(args.src_dir).expanduser().resolve()
    dst = Path(args.dst_dir).expanduser().resolve()
    dst.mkdir(parents=True, exist_ok=True)

    src_meta = src / "meta_evt6.csv"
    if not src_meta.exists():
        raise FileNotFoundError(f"missing: {src_meta}")

    # reuse waves_non to avoid recompute / disk blow-up
    src_waves_non = src / "waves_non"
    dst_waves_non = dst / "waves_non"
    if src_waves_non.exists():
        if args.link_mode == "symlink":
            _safe_symlink(src_waves_non, dst_waves_non)
        else:
            if not dst_waves_non.exists():
                shutil.copytree(str(src_waves_non), str(dst_waves_non))

    # meta_evt6.csv
    dst_meta = dst / "meta_evt6.csv"
    if args.link_mode == "symlink":
        _safe_symlink(src_meta, dst_meta)
    else:
        _safe_copy(src_meta, dst_meta)

    # generate strict split files
    df = pd.read_csv(str(src_meta), low_memory=False)
    if "_evt6" not in df.columns:
        raise ValueError("meta_evt6.csv missing column: _evt6")

    train_pc = int(args.train_per_class)
    train_pc = None if train_pc <= 0 else train_pc
    splits = _strict_split_evt6(
        df=df,
        seed=int(args.seed),
        val_per_class=int(args.val_per_class),
        test_per_class=int(args.test_per_class),
        train_per_class=train_pc,
    )
    for split, sdf in splits.items():
        sdf.to_csv(str(dst / f"meta_evt6_{split}.csv"), index=False)

    if bool(args.test_from_val):
        vdf = pd.read_csv(str(dst / "meta_evt6_val.csv"), low_memory=False)
        vdf.to_csv(str(dst / "meta_evt6_test.csv"), index=False)

    # record
    src_record = _load_record(src / "selection_record_evt6.json")
    record = dict(src_record) if isinstance(src_record, dict) else {}
    record["protocol_source"] = str(src)
    record["protocol_created_by"] = "tools/create_evt6_protocol_dir.py"
    record["strict_split"] = {
        "seed": int(args.seed),
        "val_per_class": int(args.val_per_class),
        "test_per_class": int(args.test_per_class),
        "train_per_class": int(args.train_per_class) if int(args.train_per_class) > 0 else None,
        "test_from_val": bool(args.test_from_val),
    }
    try:
        record["dst_dir"] = str(dst)
        record["dst_counts"] = pd.read_csv(str(dst / "meta_evt6.csv"), low_memory=False)["_evt6"].value_counts().sort_index().to_dict()
    except Exception:
        pass
    with open(dst / "selection_record_evt6.json", "w", encoding="utf-8") as f:
        json.dump(record, f, ensure_ascii=False, indent=2)

    print("[OK] created EVT6 protocol dir")
    print("src:", src)
    print("dst:", dst)
    print("test_from_val:", bool(args.test_from_val))
    print("meta splits:", [str(dst / f"meta_evt6_{s}.csv") for s in ("train", "val", "test")])


if __name__ == "__main__":
    main()
