#!/usr/bin/env python3
"""
EVT6 stratified analysis (magnitude / distance) for seismic cross-application reporting.

Design goals:
- Do NOT modify training/testing code paths.
- Prefer working directly on an existing run's `test_results_*.csv`.
- Produce paper-friendly artifacts: per-bin accuracy/macro-F1/per-class F1, confusion matrix.

Inputs:
- `test_results_*.csv` generated by the main pipeline (recommended), containing:
  - `tgt_evt6`, `pred_evt6`
  - stratify columns: `mag`, `Pg_dist` (optional: `Sg_dist`)
  - optional: `prob_evt6_0..5` (not required for stratified metrics)

Outputs (in --out_dir):
- `strat_<field>_<scheme>.csv`  (per-bin overall metrics)
- `strat_<field>_<scheme>_per_class_f1.csv`
- `strat_<field>_<scheme>_confusion_matrix_bin-<i>.csv` for each bin
- `STRATIFIED_REPORT.md` (template filled with tables + bin definitions)
"""

from __future__ import annotations

import argparse
import csv
import math
import os
from dataclasses import dataclass
from typing import Dict, List, Tuple


EVT6_ID2NAME = {0: "eq", 1: "ep", 2: "co", 3: "sp", 4: "se", 5: "ot"}
EVT6_CLASSES = list(range(6))


def _is_missing(v: str) -> bool:
    if v is None:
        return True
    s = str(v).strip()
    return s == "" or s.lower() == "nan"


def _to_float(v: str) -> float | None:
    if _is_missing(v):
        return None
    try:
        f = float(v)
        if not math.isfinite(f):
            return None
        return f
    except Exception:
        return None


def _to_int(v: str) -> int | None:
    if _is_missing(v):
        return None
    try:
        return int(float(v))
    except Exception:
        return None


@dataclass
class Bin:
    left: float
    right: float
    label: str

    def contains(self, x: float) -> bool:
        # left-inclusive, right-exclusive; last bin can be closed by using inf.
        return (x >= self.left) and (x < self.right)


def _quantile_bins(values: List[float], n_bins: int) -> List[Bin]:
    assert n_bins >= 2
    v = sorted(values)
    n = len(v)
    if n == 0:
        return []

    # inclusive quantiles on [0..1]
    qs = [i / n_bins for i in range(n_bins + 1)]

    def q(qv: float) -> float:
        if n == 1:
            return v[0]
        pos = qv * (n - 1)
        lo = int(pos)
        hi = min(lo + 1, n - 1)
        w = pos - lo
        return v[lo] * (1 - w) + v[hi] * w

    cuts = [q(qv) for qv in qs]
    # Ensure strictly increasing by nudging (rare ties).
    eps = 1e-9
    for i in range(1, len(cuts)):
        if cuts[i] <= cuts[i - 1]:
            cuts[i] = cuts[i - 1] + eps

    bins: List[Bin] = []
    for i in range(n_bins):
        l, r = cuts[i], cuts[i + 1]
        label = f"q{i:02d}:[{l:.4g},{r:.4g})"
        bins.append(Bin(left=l, right=r, label=label))
    # Make last bin right closed by using +inf in contains semantics (right-exclusive).
    bins[-1] = Bin(left=bins[-1].left, right=float("inf"), label=f"q{n_bins-1:02d}:[{bins[-1].left:.4g},inf)")
    return bins


def _fixed_bins(field: str) -> List[Bin]:
    f = field.lower().strip()
    if f == "mag":
        # readable bins; can be adjusted in paper
        return [
            Bin(-float("inf"), 1.0, "mag<1"),
            Bin(1.0, 2.0, "1<=mag<2"),
            Bin(2.0, 3.0, "2<=mag<3"),
            Bin(3.0, float("inf"), "mag>=3"),
        ]
    if f in ("pg_dist", "pgdist", "distance", "dist"):
        return [
            Bin(-float("inf"), 50.0, "dist<50km"),
            Bin(50.0, 100.0, "50<=dist<100km"),
            Bin(100.0, 200.0, "100<=dist<200km"),
            Bin(200.0, float("inf"), "dist>=200km"),
        ]
    if f in ("sg_dist", "sgdist"):
        return [
            Bin(-float("inf"), 50.0, "Sg_dist<50km"),
            Bin(50.0, 100.0, "50<=Sg_dist<100km"),
            Bin(100.0, 200.0, "100<=Sg_dist<200km"),
            Bin(200.0, float("inf"), "Sg_dist>=200km"),
        ]
    raise ValueError(f"unknown field for fixed bins: {field}")


def _confusion(y_true: List[int], y_pred: List[int], num_classes: int = 6) -> List[List[int]]:
    m = [[0 for _ in range(num_classes)] for __ in range(num_classes)]
    for t, p in zip(y_true, y_pred):
        if 0 <= t < num_classes and 0 <= p < num_classes:
            m[t][p] += 1
    return m


def _per_class_f1(cm: List[List[int]]) -> Dict[int, Dict[str, float]]:
    out: Dict[int, Dict[str, float]] = {}
    num_classes = len(cm)
    col_sums = [sum(cm[r][c] for r in range(num_classes)) for c in range(num_classes)]
    row_sums = [sum(cm[r]) for r in range(num_classes)]
    for k in range(num_classes):
        tp = cm[k][k]
        fp = col_sums[k] - tp
        fn = row_sums[k] - tp
        prec = tp / (tp + fp) if (tp + fp) > 0 else 0.0
        rec = tp / (tp + fn) if (tp + fn) > 0 else 0.0
        f1 = (2 * prec * rec / (prec + rec)) if (prec + rec) > 0 else 0.0
        out[k] = {"precision": prec, "recall": rec, "f1": f1, "support": float(row_sums[k])}
    return out


def _accuracy(y_true: List[int], y_pred: List[int]) -> float:
    if not y_true:
        return 0.0
    ok = sum(1 for t, p in zip(y_true, y_pred) if t == p)
    return ok / len(y_true)


def _macro_f1(per_class: Dict[int, Dict[str, float]]) -> float:
    f1s = [per_class[k]["f1"] for k in EVT6_CLASSES]
    return sum(f1s) / len(f1s) if f1s else 0.0


def _write_csv(path: str, rows: List[Dict[str, object]], fieldnames: List[str]):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        for r in rows:
            w.writerow(r)


def _write_cm_csv(path: str, cm: List[List[int]]):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    header = ["tgt\\pred"] + [EVT6_ID2NAME[i] for i in EVT6_CLASSES]
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(header)
        for i in EVT6_CLASSES:
            w.writerow([EVT6_ID2NAME[i]] + cm[i])


def _load_rows(csv_path: str) -> Tuple[List[Dict[str, str]], List[str]]:
    with open(csv_path, "r", newline="", encoding="utf-8") as f:
        r = csv.DictReader(f)
        rows = [row for row in r]
    return rows, list(rows[0].keys()) if rows else ([], [])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--test_results_csv", required=True, help="Path to test_results_*.csv")
    ap.add_argument("--out_dir", required=True, help="Output directory for stratified analysis artifacts")
    ap.add_argument("--field", default="mag", help="Stratify field: mag / Pg_dist / Sg_dist")
    ap.add_argument("--scheme", default="quantile", choices=["quantile", "fixed"], help="Binning scheme")
    ap.add_argument("--n_bins", type=int, default=5, help="Number of bins for quantile scheme (default 5)")
    ap.add_argument("--min_bin_size", type=int, default=50, help="Warn if a bin has < min_bin_size samples")
    args = ap.parse_args()

    test_csv = os.path.abspath(args.test_results_csv)
    out_dir = os.path.abspath(args.out_dir)
    os.makedirs(out_dir, exist_ok=True)

    rows, cols = _load_rows(test_csv)
    if not rows:
        raise RuntimeError(f"empty csv: {test_csv}")

    field = str(args.field).strip()
    if field not in cols:
        raise KeyError(f"field '{field}' not found in test_results columns. available={len(cols)}")
    for k in ("tgt_evt6", "pred_evt6"):
        if k not in cols:
            raise KeyError(f"missing required column: {k}")

    # collect usable values for binning
    xs_all: List[float] = []
    for r in rows:
        x = _to_float(r.get(field))
        if x is not None:
            xs_all.append(x)

    if not xs_all:
        raise RuntimeError(f"no valid numeric values for field={field} in {test_csv}")

    if args.scheme == "quantile":
        bins = _quantile_bins(xs_all, n_bins=int(args.n_bins))
        scheme_tag = f"quantile{int(args.n_bins)}"
    else:
        bins = _fixed_bins(field)
        scheme_tag = "fixed"

    # assign rows into bins (missing field values are skipped)
    bin_items: List[List[Dict[str, str]]] = [[] for _ in bins]
    skipped_missing = 0
    for r in rows:
        x = _to_float(r.get(field))
        if x is None:
            skipped_missing += 1
            continue
        placed = False
        for i, b in enumerate(bins):
            if b.contains(x):
                bin_items[i].append(r)
                placed = True
                break
        if not placed:
            # should not happen with last bin inf
            skipped_missing += 1

    overall_rows = []
    perclass_rows = []

    for i, (b, items) in enumerate(zip(bins, bin_items)):
        y_true: List[int] = []
        y_pred: List[int] = []
        for r in items:
            t = _to_int(r.get("tgt_evt6"))
            p = _to_int(r.get("pred_evt6"))
            if t is None or p is None:
                continue
            if 0 <= t < 6 and 0 <= p < 6:
                y_true.append(t)
                y_pred.append(p)

        cm = _confusion(y_true, y_pred, num_classes=6)
        pc = _per_class_f1(cm)
        acc = _accuracy(y_true, y_pred)
        mf1 = _macro_f1(pc)

        if len(y_true) < int(args.min_bin_size):
            # keep this as a data artifact; the report will mention low-support bins.
            pass

        overall_rows.append(
            {
                "bin_id": i,
                "bin_label": b.label,
                "field": field,
                "scheme": scheme_tag,
                "n_total_in_bin": len(items),
                "n_used_for_metrics": len(y_true),
                "accuracy": round(acc, 6),
                "macro_f1": round(mf1, 6),
            }
        )

        for k in EVT6_CLASSES:
            perclass_rows.append(
                {
                    "bin_id": i,
                    "bin_label": b.label,
                    "class_id": k,
                    "class_name": EVT6_ID2NAME[k],
                    "support": int(pc[k]["support"]),
                    "precision": round(pc[k]["precision"], 6),
                    "recall": round(pc[k]["recall"], 6),
                    "f1": round(pc[k]["f1"], 6),
                }
            )

        cm_path = os.path.join(out_dir, f"strat_{field}_{scheme_tag}_confusion_matrix_bin-{i}.csv")
        _write_cm_csv(cm_path, cm)

    overall_path = os.path.join(out_dir, f"strat_{field}_{scheme_tag}.csv")
    perclass_path = os.path.join(out_dir, f"strat_{field}_{scheme_tag}_per_class_f1.csv")
    _write_csv(
        overall_path,
        overall_rows,
        fieldnames=["bin_id", "bin_label", "field", "scheme", "n_total_in_bin", "n_used_for_metrics", "accuracy", "macro_f1"],
    )
    _write_csv(
        perclass_path,
        perclass_rows,
        fieldnames=["bin_id", "bin_label", "class_id", "class_name", "support", "precision", "recall", "f1"],
    )

    # Markdown report (template-like)
    md_path = os.path.join(out_dir, "STRATIFIED_REPORT.md")
    with open(md_path, "w", encoding="utf-8") as f:
        f.write("# EVT6 Stratified Analysis Report\n\n")
        f.write(f"- test_results: `{test_csv}`\n")
        f.write(f"- field: `{field}`\n")
        f.write(f"- scheme: `{scheme_tag}`\n")
        f.write(f"- total rows: {len(rows)}\n")
        f.write(f"- skipped (missing `{field}`): {skipped_missing}\n\n")

        f.write("## Bin definitions\n\n")
        for i, b in enumerate(bins):
            f.write(f"- bin {i}: {b.label}\n")
        f.write("\n")

        f.write("## Per-bin overall metrics\n\n")
        f.write(f"See `{os.path.basename(overall_path)}`.\n\n")

        f.write("## Per-bin per-class F1\n\n")
        f.write(f"See `{os.path.basename(perclass_path)}`.\n\n")

        f.write("## Per-bin confusion matrices\n\n")
        f.write("Files:\n")
        for i in range(len(bins)):
            f.write(f"- `strat_{field}_{scheme_tag}_confusion_matrix_bin-{i}.csv`\n")
        f.write("\n")

        f.write("## Notes for paper writing\n\n")
        f.write("- Prefer quantile bins for stable sample sizes; fixed bins for interpretability.\n")
        f.write("- If some bins have small supports, report them but interpret cautiously.\n")

    print("[OK] wrote:")
    print(" -", overall_path)
    print(" -", perclass_path)
    print(" -", md_path)


if __name__ == "__main__":
    main()

